services:
  enct-gpu:
    image: enct-gpu:latest
    container_name: enct-gpu
    working_dir: /app
    entrypoint: .venv/bin/python3 -m enct batch
    environment:
      PY_ENV: prod
      CONFIG_PATH: /mnt/app/encoding_conf.yaml
      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${BASE_DIR_PATH}:/mnt/volume/app"
      - "${CONFIG_PATH}:/mnt/app/encoding_conf.yaml"
    labels:
      app: enct
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu,video]
